import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Global background video */}
        <div className="fixed inset-0 -z-20 pointer-events-none">
          <video autoPlay muted loop playsInline className="w-full h-full object-cover">
            <source src="https://videos.pexels.com/video-files/3571468/3571468-sd_640_360_30fps.mp4" type="video/mp4" />
            <source src="https://videos.pexels.com/video-files/3571468/3571468-sd_640_360_30fps.webm" type="video/webm" />
          </video>
        </div>
        {/* Subtle dark overlay for readability */}
        <div className="fixed inset-0 -z-10 pointer-events-none bg-black/40" />
        {children}
      </body>
    </html>
  );
}
